production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
      options:
        max_pool_size: <%= (ENV['MONGO_POOL_SIZE']||"10").to_i %>
        heartbeat_frequency: 1
        write:
          w: 1
        read:
          mode: <%= ENV['MONGO_READ_MODE']||"primary" %>

development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      uri: <%= ENV['MONGO_URL'] %>
      options:
        max_pool_size: <%= (ENV['MONGO_POOL_SIZE']||"10").to_i %>
        heartbeat_frequency: 1
        write:
          w: 1
        read:
          mode: <%= ENV['MONGO_READ_MODE']||"primary" %>

test:
  clients:
    default:
      database: srjlol_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
